---@class SpellSlot
---@field public Q SpellSlot
---@field public W SpellSlot
---@field public E SpellSlot
---@field public R SpellSlot
---@field public Summoner1 SpellSlot
---@field public Summoner2 SpellSlot
---@field public Item1 SpellSlot
---@field public Item2 SpellSlot
---@field public Item3 SpellSlot
---@field public Item4 SpellSlot
---@field public Item5 SpellSlot
---@field public Item6 SpellSlot
---@field public Trinket SpellSlot
---@field public Recall SpellSlot
---@field public SpecialAttack SpellSlot
---@field public BasicAttack SpellSlot
---@field public Invalid SpellSlot

---@type SpellSlot
_G.SpellSlot = {}